### ISSUE TITLE
Unable to buid on mac OS X 11

### ISSUE THREAD

**Issue by sadatanwer** [deeplearning4j/libnd4j#79]
I am unable to build the lib on a mac OS X for cpu
I am getting the following linker error when i run` ./buildnativeoperations.sh blas cpu`
[Error Gist](https://gist.github.com/sadatanwer/abd6bc5afa4a3a8cf012a3e129c462b8)
I have already installed the required clang and have also added the following environment variables
[Env Variables](https://gist.github.com/sadatanwer/c03f06010c717b211383e562ae6d6bd9)
and now I am completely lost! Any help is much appreciated
Thanks

**Comment by linkerlin** [comment]
I cannot build it on my ubuntu 15.10 .
It's very hard to build.

**Comment by treo** [comment]
@linkerlin building on ubuntu works fine. If you have problems, come to the gitter, and we can help you there.

**Comment by linkerlin** [comment]
I got error msg:

./buildnativeoperations.sh blas cpu
eval cmake
Running blas
RUNNING COMMAND cmake
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
ADDING BLAS
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CPU BLAS
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linker/gits/libnd4j/blasbuild/cpu
/home/linker/Downloads/cmake-3.5.1-Linux-x86_64/bin/cmake -H/home/linker/gits/libnd4j -B/home/linker/gits/libnd4j/blasbuild/cpu --check-build-system CMakeFiles/Makefile.cmake 0
/home/linker/Downloads/cmake-3.5.1-Linux-x86_64/bin/cmake -E cmake_progress_start /home/linker/gits/libnd4j/blasbuild/cpu/CMakeFiles /home/linker/gits/libnd4j/blasbuild/cpu/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/linker/gits/libnd4j/blasbuild/cpu'
make -f blas/CMakeFiles/nd4j.dir/build.make blas/CMakeFiles/nd4j.dir/depend
make[2]: Entering directory '/home/linker/gits/libnd4j/blasbuild/cpu'
cd /home/linker/gits/libnd4j/blasbuild/cpu && /home/linker/Downloads/cmake-3.5.1-Linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /home/linker/gits/libnd4j /home/linker/gits/libnd4j/blas /home/linker/gits/libnd4j/blasbuild/cpu /home/linker/gits/libnd4j/blasbuild/cpu/blas /home/linker/gits/libnd4j/blasbuild/cpu/blas/CMakeFiles/nd4j.dir/DependInfo.cmake --color=
Scanning dependencies of target nd4j
make[2]: Leaving directory '/home/linker/gits/libnd4j/blasbuild/cpu'
make -f blas/CMakeFiles/nd4j.dir/build.make blas/CMakeFiles/nd4j.dir/build
make[2]: Entering directory '/home/linker/gits/libnd4j/blasbuild/cpu'
[ 33%] Building CXX object blas/CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o
cd /home/linker/gits/libnd4j/blasbuild/cpu/blas && /usr/bin/g++   -D__CPUBLAS__=true -Dnd4j_EXPORTS -I/home/linker/gits/libnd4j/include -I/home/linker/gits/libnd4j/blas/../include -I/usr/local/include  -Wall -g  -fopenmp -std=c++11  -fassociative-math -funsafe-math-optimizations -march=native -fopenmp -O3 -ffast-math -ftree-vectorize -msse2 -ftree-vectorizer-verbose=2 -fopt-info-vec -fopt-info-vec-missed -fPIC   -o CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o -c /home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:19:5: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:18:14: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:18:14: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:41:5: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:40:18: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:40:18: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:40:18: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:40:18: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:65:5: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:64:13: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:64:13: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:88:5: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:87:12: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:87:12: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:109:5: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:108:12: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:108:12: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:139:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:148:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:156:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:164:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:176:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:182:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:193:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:199:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:211:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:217:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:238:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:248:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:260:57: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:265:59: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:278:57: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:286:59: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:302:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:313:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:329:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:337:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:350:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:357:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:371:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:379:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:393:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:401:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:426:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:440:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:460:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:475:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:494:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:507:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:526:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:539:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:558:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:571:54: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:588:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:597:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:613:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:623:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:639:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:649:54: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:666:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:676:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:693:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:704:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:721:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:731:54: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:749:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:761:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:778:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:788:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:808:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:818:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:836:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:848:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:866:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:878:54: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:904:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:917:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:936:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:949:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:967:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:978:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:996:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:1009:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:1027:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:1038:52: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:1055:50: note: not vectorized: not enough data-refs in basic block.
/home/linker/gits/libnd4j/blas/cpu/NativeBlas.cpp:1066:52: note: not vectorized: not enough data-refs in basic block.
[ 66%] Building CXX object blas/CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o
cd /home/linker/gits/libnd4j/blasbuild/cpu/blas && /usr/bin/g++   -D__CPUBLAS__=true -Dnd4j_EXPORTS -I/home/linker/gits/libnd4j/include -I/home/linker/gits/libnd4j/blas/../include -I/usr/local/include  -Wall -g  -fopenmp -std=c++11  -fassociative-math -funsafe-math-optimizations -march=native -fopenmp -O3 -ffast-math -ftree-vectorize -msse2 -ftree-vectorizer-verbose=2 -fopt-info-vec -fopt-info-vec-missed -fPIC   -o CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o -c /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp
In file included from /home/linker/gits/libnd4j/include/broadcasting.h:12:0,
                 from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:8,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/shape.h:3085:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
/home/linker/gits/libnd4j/include/shape.h:3807:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
/home/linker/gits/libnd4j/include/shape.h:3811:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:9:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/indexreduce.h:673:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma  simd
 ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:11:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/reduce.h:603:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
/home/linker/gits/libnd4j/include/reduce.h:659:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:12:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/reduce3.h:666:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/transform.h:232:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd
 ^
/home/linker/gits/libnd4j/include/transform.h:355:0: warning: ignoring #pragma simd  [-Wunknown-pragmas]
 #pragma simd 
 ^
/home/linker/gits/libnd4j/include/transform.h: In member function ‘void functions::transform::ops::IsMax<T>::doAllCuda(T*, int*, T*, int*, T*)’:
/home/linker/gits/libnd4j/include/transform.h:4371:3: error: ‘__shared__’ was not declared in this scope
   __shared__ functions::indexreduce::ops::IMax<T> *max;
   ^
/home/linker/gits/libnd4j/include/transform.h:4372:14: error: expected ‘;’ before ‘int’
   __shared__ int maxIdx;
              ^
/home/linker/gits/libnd4j/include/transform.h:4373:6: error: ‘threadIdx’ was not declared in this scope
   if(threadIdx.x == 0) {
      ^
/home/linker/gits/libnd4j/include/transform.h:4374:4: error: ‘max’ was not declared in this scope
    max = new functions::indexreduce::ops::IMax<T>();
    ^
/home/linker/gits/libnd4j/include/transform.h:4374:4: note: suggested alternative:
In file included from /usr/include/c++/4.9/vector:60:0,
                 from /home/linker/gits/libnd4j/include/transform.h:10,
                 from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   ‘std::max’
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/transform.h:4377:17: error: there are no arguments to ‘__syncthreads’ that depend on a template parameter, so a declaration of ‘__syncthreads’ must be available [-fpermissive]
   __syncthreads();
                 ^
/home/linker/gits/libnd4j/include/transform.h:4377:17: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/linker/gits/libnd4j/include/transform.h:4379:3: error: ‘max’ was not declared in this scope
   max->transform(
   ^
/home/linker/gits/libnd4j/include/transform.h:4379:3: note: suggested alternative:
In file included from /usr/include/c++/4.9/vector:60:0,
                 from /home/linker/gits/libnd4j/include/transform.h:10,
                 from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   ‘std::max’
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/transform.h:4389:17: error: there are no arguments to ‘__syncthreads’ that depend on a template parameter, so a declaration of ‘__syncthreads’ must be available [-fpermissive]
   __syncthreads();
                 ^
/home/linker/gits/libnd4j/include/transform.h:4390:6: error: ‘threadIdx’ was not declared in this scope
   if(threadIdx.x == 0)
      ^
/home/linker/gits/libnd4j/include/transform.h:4391:4: error: ‘maxIdx’ was not declared in this scope
    maxIdx = (int) result[0];
    ^
/home/linker/gits/libnd4j/include/transform.h:4392:17: error: there are no arguments to ‘__syncthreads’ that depend on a template parameter, so a declaration of ‘__syncthreads’ must be available [-fpermissive]
   __syncthreads();
                 ^
/home/linker/gits/libnd4j/include/transform.h:4394:7: error: ‘threadIdx’ was not declared in this scope
   if (threadIdx.x < shape::length(resultShapeBuffer))
       ^
/home/linker/gits/libnd4j/include/transform.h:4396:17: error: there are no arguments to ‘__syncthreads’ that depend on a template parameter, so a declaration of ‘__syncthreads’ must be available [-fpermissive]
   __syncthreads();
                 ^
/home/linker/gits/libnd4j/include/transform.h:4398:7: error: ‘threadIdx’ was not declared in this scope
   if (threadIdx.x == 0) {
       ^
/home/linker/gits/libnd4j/include/transform.h:4399:11: error: ‘maxIdx’ was not declared in this scope
    result[maxIdx] = 1.0;
           ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp: In member function ‘long long int NativeOps::mallocHost(long int, int)’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1550:20: warning: NULL used in arithmetic [-Wpointer-arith]
     if (pointer == NULL)
                    ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp: In instantiation of ‘void flattenGeneric(int, char, long long int, long long int, long long int, long long int) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1508:84:   required from here
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1432:18: warning: unused variable ‘inputOrder’ [-Wunused-variable]
             char inputOrder = shape::order(inputShapeInfoPointer);
                  ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1459:14: warning: unused variable ‘inputOrder’ [-Wunused-variable]
         char inputOrder = shape::order(inputShapeInfoPointer);
              ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1393:10: warning: unused variable ‘stride’ [-Wunused-variable]
     int *stride = shape::stride(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1395:10: warning: unused variable ‘squeezed’ [-Wunused-variable]
     bool squeezed = false;
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1407:10: warning: unused variable ‘coord’ [-Wunused-variable]
     int *coord = (int *) malloc(sizeof(int) * rank);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1408:10: warning: unused variable ‘xShape’ [-Wunused-variable]
     int *xShape = shape::shapeOf(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1409:10: warning: unused variable ‘xStride’ [-Wunused-variable]
     int *xStride = shape::stride(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1410:10: warning: unused variable ‘resultOrder’ [-Wunused-variable]
     char resultOrder = shape::order(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp: In instantiation of ‘void flattenGeneric(int, char, long long int, long long int, long long int, long long int) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1530:85:   required from here
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1432:18: warning: unused variable ‘inputOrder’ [-Wunused-variable]
             char inputOrder = shape::order(inputShapeInfoPointer);
                  ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1459:14: warning: unused variable ‘inputOrder’ [-Wunused-variable]
         char inputOrder = shape::order(inputShapeInfoPointer);
              ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1393:10: warning: unused variable ‘stride’ [-Wunused-variable]
     int *stride = shape::stride(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1395:10: warning: unused variable ‘squeezed’ [-Wunused-variable]
     bool squeezed = false;
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1407:10: warning: unused variable ‘coord’ [-Wunused-variable]
     int *coord = (int *) malloc(sizeof(int) * rank);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1408:10: warning: unused variable ‘xShape’ [-Wunused-variable]
     int *xShape = shape::shapeOf(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1409:10: warning: unused variable ‘xStride’ [-Wunused-variable]
     int *xStride = shape::stride(inputShapeInfoPointer);
          ^
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1410:10: warning: unused variable ‘resultOrder’ [-Wunused-variable]
     char resultOrder = shape::order(inputShapeInfoPointer);
          ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:8:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/broadcasting.h: In instantiation of ‘void functions::broadcast::Broadcast<T>::exec(T*, int*, T*, int*, T*, int*, int*, int) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:110:9:   required from ‘void NativeOpExcutioner<T>::execBroadcast(int, T*, int*, T*, int*, T*, int*, int*, int) [with T = double]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:124:28:   required from here
/home/linker/gits/libnd4j/include/broadcasting.h:290:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeInfo);
         ^
/home/linker/gits/libnd4j/include/broadcasting.h:278:8: warning: unused variable ‘stride’ [-Wunused-variable]
   int *stride = shape::stride(xShapeInfo);
        ^
/home/linker/gits/libnd4j/include/broadcasting.h:321:7: warning: unused variable ‘tadLength’ [-Wunused-variable]
   int tadLength = shape::length(tadShapeShapeInfo);
       ^
/home/linker/gits/libnd4j/include/broadcasting.h:322:7: warning: unused variable ‘rank’ [-Wunused-variable]
   int rank = shape::rank(tadShapeShapeInfo);
       ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:10:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/pairwise_transform.h: In instantiation of ‘void functions::pairwise_transforms::PairWiseTransform<T>::exec(T*, int*, T*, int*, T*, int*, T*) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:169:9:   required from ‘void NativeOpExcutioner<T>::execPairwiseTransform(int, T*, int*, T*, int*, T*, int*, T*) [with T = double]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:246:31:   required from here
/home/linker/gits/libnd4j/include/pairwise_transform.h:470:9: warning: unused variable ‘yShape’ [-Wunused-variable]
    int *yShape = shape::shapeOf(yShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:471:9: warning: unused variable ‘resultShape’ [-Wunused-variable]
    int *resultShape = shape::shapeOf(resultShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:477:8: warning: unused variable ‘xRank’ [-Wunused-variable]
    int xRank = shape::rank(xShapeBuffer);
        ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:478:8: warning: unused variable ‘yRank’ [-Wunused-variable]
    int yRank = shape::rank(yShapeBuffer);
        ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:479:8: warning: unused variable ‘resultRank’ [-Wunused-variable]
    int resultRank = shape::rank(resultShapeBuffer);
        ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:482:9: warning: unused variable ‘xOrder’ [-Wunused-variable]
    char xOrder = shape::order(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:483:9: warning: unused variable ‘yOrder’ [-Wunused-variable]
    char yOrder = shape::order(yShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:484:9: warning: unused variable ‘resultOrder’ [-Wunused-variable]
    char resultOrder = shape::order(resultShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:534:9: warning: unused variable ‘xOrder’ [-Wunused-variable]
    char xOrder = shape::order(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:535:9: warning: unused variable ‘yOrder’ [-Wunused-variable]
    char yOrder = shape::order(yShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:536:9: warning: unused variable ‘resultOrder’ [-Wunused-variable]
    char resultOrder = shape::order(resultShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:552:9: warning: unused variable ‘resultStride’ [-Wunused-variable]
    int *resultStride = shape::stride(resultShapeBuffer);
         ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:11:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/reduce.h: In instantiation of ‘void functions::reduce::ReduceFunction<T>::exec(T*, int*, T*, T*, int*, int*, int) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:236:9:   required from ‘void NativeOpExcutioner<T>::execReduce(int, T*, int*, T*, T*, int*, int*, int) [with T = double]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:300:179:   required from here
/home/linker/gits/libnd4j/include/reduce.h:799:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeInfo);
         ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:13:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/summarystatsreduce.h: In instantiation of ‘void functions::summarystats::SummaryStatsReduce<T>::exec(T*, int*, T*, T*, int*, int*, int) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:485:9:   required from ‘void NativeOpExcutioner<T>::execSummaryStats(int, T*, int*, T*, T*, int*, int*, int, bool) [with T = double]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:610:42:   required from here
/home/linker/gits/libnd4j/include/summarystatsreduce.h:1010:26: warning: unused variable ‘stride’ [-Wunused-variable]
                     int *stride = shape::stride(xShapeInfo);
                          ^
/home/linker/gits/libnd4j/include/summarystatsreduce.h:1046:25: warning: unused variable ‘tadLength’ [-Wunused-variable]
                     int tadLength = shape::length(tadShapeShapeInfo);
                         ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:8:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/broadcasting.h: In instantiation of ‘void functions::broadcast::Broadcast<T>::exec(T*, int*, T*, int*, T*, int*, int*, int) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:110:9:   required from ‘void NativeOpExcutioner<T>::execBroadcast(int, T*, int*, T*, int*, T*, int*, int*, int) [with T = float]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:778:189:   required from here
/home/linker/gits/libnd4j/include/broadcasting.h:290:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeInfo);
         ^
/home/linker/gits/libnd4j/include/broadcasting.h:278:8: warning: unused variable ‘stride’ [-Wunused-variable]
   int *stride = shape::stride(xShapeInfo);
        ^
/home/linker/gits/libnd4j/include/broadcasting.h:321:7: warning: unused variable ‘tadLength’ [-Wunused-variable]
   int tadLength = shape::length(tadShapeShapeInfo);
       ^
/home/linker/gits/libnd4j/include/broadcasting.h:322:7: warning: unused variable ‘rank’ [-Wunused-variable]
   int rank = shape::rank(tadShapeShapeInfo);
       ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:10:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/pairwise_transform.h: In instantiation of ‘void functions::pairwise_transforms::PairWiseTransform<T>::exec(T*, int*, T*, int*, T*, int*, T*) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:169:9:   required from ‘void NativeOpExcutioner<T>::execPairwiseTransform(int, T*, int*, T*, int*, T*, int*, T*) [with T = float]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:904:183:   required from here
/home/linker/gits/libnd4j/include/pairwise_transform.h:470:9: warning: unused variable ‘yShape’ [-Wunused-variable]
    int *yShape = shape::shapeOf(yShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:471:9: warning: unused variable ‘resultShape’ [-Wunused-variable]
    int *resultShape = shape::shapeOf(resultShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:477:8: warning: unused variable ‘xRank’ [-Wunused-variable]
    int xRank = shape::rank(xShapeBuffer);
        ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:478:8: warning: unused variable ‘yRank’ [-Wunused-variable]
    int yRank = shape::rank(yShapeBuffer);
        ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:479:8: warning: unused variable ‘resultRank’ [-Wunused-variable]
    int resultRank = shape::rank(resultShapeBuffer);
        ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:482:9: warning: unused variable ‘xOrder’ [-Wunused-variable]
    char xOrder = shape::order(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:483:9: warning: unused variable ‘yOrder’ [-Wunused-variable]
    char yOrder = shape::order(yShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:484:9: warning: unused variable ‘resultOrder’ [-Wunused-variable]
    char resultOrder = shape::order(resultShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:534:9: warning: unused variable ‘xOrder’ [-Wunused-variable]
    char xOrder = shape::order(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:535:9: warning: unused variable ‘yOrder’ [-Wunused-variable]
    char yOrder = shape::order(yShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:536:9: warning: unused variable ‘resultOrder’ [-Wunused-variable]
    char resultOrder = shape::order(resultShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/pairwise_transform.h:552:9: warning: unused variable ‘resultStride’ [-Wunused-variable]
    int *resultStride = shape::stride(resultShapeBuffer);
         ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:11:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/reduce.h: In instantiation of ‘void functions::reduce::ReduceFunction<T>::exec(T*, int*, T*, T*, int*, int*, int) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:236:9:   required from ‘void NativeOpExcutioner<T>::execReduce(int, T*, int*, T*, T*, int*, int*, int) [with T = float]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:930:157:   required from here
/home/linker/gits/libnd4j/include/reduce.h:799:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeInfo);
         ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:13:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/summarystatsreduce.h: In instantiation of ‘void functions::summarystats::SummaryStatsReduce<T>::exec(T*, int*, T*, T*, int*, int*, int) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:485:9:   required from ‘void NativeOpExcutioner<T>::execSummaryStats(int, T*, int*, T*, T*, int*, int*, int, bool) [with T = float]’
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1280:26:   required from here
/home/linker/gits/libnd4j/include/summarystatsreduce.h:1010:26: warning: unused variable ‘stride’ [-Wunused-variable]
                     int *stride = shape::stride(xShapeInfo);
                          ^
/home/linker/gits/libnd4j/include/summarystatsreduce.h:1046:25: warning: unused variable ‘tadLength’ [-Wunused-variable]
                     int tadLength = shape::length(tadShapeShapeInfo);
                         ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::IsMax<T>::execSpecial(T*, int*, T*, int*, T*) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:4690:49: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
   if(extraParams == NULL || extraParams[0] == 0 || extraParams[0] == 1 && extraParams[1] == shape::MAX_DIMENSION) {
                                                 ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::SoftMaxDerivative<T>::execSpecial(T*, int*, T*, int*, T*) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:4170:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::SoftMax<T>::execSpecial(T*, int*, T*, int*, T*) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:3693:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::Col2Im<T>::execSpecial(T*, int*, T*, int*, T*) [with T = float]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:3367:7: warning: unused variable ‘imgHeight’ [-Wunused-variable]
   int imgHeight = (int) extraParams[4];
       ^
/home/linker/gits/libnd4j/include/transform.h:3368:7: warning: unused variable ‘imgWidth’ [-Wunused-variable]
   int imgWidth = (int) extraParams[5];
       ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::IsMax<T>::execSpecial(T*, int*, T*, int*, T*) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:4690:49: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
   if(extraParams == NULL || extraParams[0] == 0 || extraParams[0] == 1 && extraParams[1] == shape::MAX_DIMENSION) {
                                                 ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::SoftMaxDerivative<T>::execSpecial(T*, int*, T*, int*, T*) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:4170:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::SoftMax<T>::execSpecial(T*, int*, T*, int*, T*) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:3693:9: warning: unused variable ‘stride’ [-Wunused-variable]
    int *stride = shape::stride(xShapeBuffer);
         ^
/home/linker/gits/libnd4j/include/transform.h: In instantiation of ‘void functions::transform::ops::Col2Im<T>::execSpecial(T*, int*, T*, int*, T*) [with T = double]’:
/home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:1591:1:   required from here
/home/linker/gits/libnd4j/include/transform.h:3367:7: warning: unused variable ‘imgHeight’ [-Wunused-variable]
   int imgHeight = (int) extraParams[4];
       ^
/home/linker/gits/libnd4j/include/transform.h:3368:7: warning: unused variable ‘imgWidth’ [-Wunused-variable]
   int imgWidth = (int) extraParams[5];
       ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:12:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/reduce3.h: At global scope:
/home/linker/gits/libnd4j/include/reduce3.h:95:11: warning: inline function ‘T functions::reduce3::Reduce3<T>::update(T, T, T**) [with T = double]’ used but never defined
  inline T update(T old, T opOutput, T **extraParamsRef) = 0;
           ^
/home/linker/gits/libnd4j/include/reduce3.h:80:11: warning: inline function ‘T functions::reduce3::Reduce3<T>::op(T, T, T**) [with T = double]’ used but never defined
  inline T op(T d1, T d2, T **extraParamsRef) = 0;
           ^
/home/linker/gits/libnd4j/include/reduce3.h:48:11: warning: inline function ‘T functions::reduce3::Reduce3<T>::postProcess(T, int, T**) [with T = double]’ used but never defined
  inline T postProcess(T reduction, int n,T **extraParamsRef) = 0;
           ^
In file included from /home/linker/gits/libnd4j/include/transform.h:17:0,
                 from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/scalar.h:43:22: warning: inline function ‘T functions::scalar::ScalarTransform<T>::op(T, T, T*) [with T = double]’ used but never defined
             inline T op(T d1, T d2, T *params) = 0;
                      ^
In file included from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:12:0,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/reduce3.h:95:11: warning: inline function ‘T functions::reduce3::Reduce3<T>::update(T, T, T**) [with T = float]’ used but never defined
  inline T update(T old, T opOutput, T **extraParamsRef) = 0;
           ^
/home/linker/gits/libnd4j/include/reduce3.h:80:11: warning: inline function ‘T functions::reduce3::Reduce3<T>::op(T, T, T**) [with T = float]’ used but never defined
  inline T op(T d1, T d2, T **extraParamsRef) = 0;
           ^
/home/linker/gits/libnd4j/include/reduce3.h:48:11: warning: inline function ‘T functions::reduce3::Reduce3<T>::postProcess(T, int, T**) [with T = float]’ used but never defined
  inline T postProcess(T reduction, int n,T **extraParamsRef) = 0;
           ^
In file included from /home/linker/gits/libnd4j/include/transform.h:17:0,
                 from /home/linker/gits/libnd4j/blas/cpu/../NativeOpExcutioner.h:14,
                 from /home/linker/gits/libnd4j/blas/cpu/NativeOps.cpp:6:
/home/linker/gits/libnd4j/include/scalar.h:43:22: warning: inline function ‘T functions::scalar::ScalarTransform<T>::op(T, T, T*) [with T = float]’ used but never defined
             inline T op(T d1, T d2, T *params) = 0;
                      ^
blas/CMakeFiles/nd4j.dir/build.make:89: recipe for target 'blas/CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o' failed
make[2]: *** [blas/CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o] Error 1
make[2]: Leaving directory '/home/linker/gits/libnd4j/blasbuild/cpu'
CMakeFiles/Makefile2:106: recipe for target 'blas/CMakeFiles/nd4j.dir/all' failed
make[1]: *** [blas/CMakeFiles/nd4j.dir/all] Error 2
make[1]: Leaving directory '/home/linker/gits/libnd4j/blasbuild/cpu'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2
FINISHING BUILD

**Comment by treo** [comment]
Are you on the current master with this? Because it builds fine for me.

**Comment by linkerlin** [comment]
On my mac book pro and my ubuntu box, I just pull the current master repo, and I got it ok both with AppleClang(AppleClang++) and with clang-omp(clang-omp++).
Thank you for your hint, @treo !
**I found out Apple Clang 7.3.0 can be used as a replacement for clang-imp.
** @sadatanwer

**Comment by linkerlin** [comment]
@treo I think I found out the reason of "Killed" .
The ptxas running out of memory, because I set a 1.5GB swap and the ubuntu box only have a 4G memory.
Added a new 12GB swapfile solved the problem.
Thank you for your help.
P.S.
The clang-omp is not a necessary compiler if mac has the newest Xcode/AppleClang.

**Comment by agibsonccc** [comment]
@linkerlin thanks! Could you send us a pull request for updating some of the things you've found for different versions of clang on mac?

**Comment by linkerlin** [comment]
I will have a try and a test.

**Comment by agibsonccc** [comment]
FWIW everything is still building for me.

**Comment by agibsonccc** [comment]
Update on this?

**Comment by sadatanwer** [comment]
No! :( I still get the same issue, I have no clue what its trying to link with. :(

**Comment by sadatanwer** [comment]
@linkerlin 
Can you help me a little here, this is what I get when I start the build process 
/buildnativeoperations.sh blas cpu
eval cmake
RUNNING OSX CLANG
Running blas
RUNNING COMMAND cmake
-- The C compiler identification is AppleClang 7.3.0.7030029
-- The CXX compiler identification is Clang 3.5.0
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp++
-- Check for working CXX compiler: /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
ADDING BLAS
Using apple
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
CPU BLAS
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Configuring done
-- Generating done

Something there doesnot look right, its taking the AppleClang and also clang 3.5 and is completely confused in the ADDING BLAS using Apple part, do you have any idea what I am missing? any help would be really appreciated!

**Comment by sadatanwer** [comment]
Okay, so I got the OpenMP issue to work, so now  now more failed status there, but that still did not fix my linking issue, I tried running the link command with the -v command and here is what it looks like 

```
clang-omp++  -Wall -fopenmp -std=c++11 -L/usr/local/Cellar/libiomp/20150701/lib -fassociative-math -funsafe-math-optimizations -march=native   -O3 -ffast-math -ftree-vectorize -msse2 -dynamiclib -Wl,-headerpad_max_install_names  -o libnd4j.dylib -install_name @rpath/libnd4j.dylib CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o -framework Accelerate -framework Accelerate -v
clang version 3.5.0 
Target: x86_64-apple-darwin15.4.0
Thread model: posix
 "/usr/bin/ld" -dynamic -dylib -arch x86_64 -dylib_install_name @rpath/libnd4j.dylib -macosx_version_min 10.11.0 -o libnd4j.dylib -L/usr/local/Cellar/libiomp/20150701/lib -liomp5 -headerpad_max_install_names CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o -framework Accelerate -framework Accelerate -L/usr/local/Cellar/clang-omp/2015-04-01/libexec/lib -L/usr/local/Cellar/libiomp/20150701/lib -L/usr/local/Cellar/clang-omp/2015-04-01/libexec/lib -L/usr/local/Cellar/libiomp/20150701/include/libiomp -L/usr/local/Cellar/clang-omp/2015-04-01/libexec/lib -L/usr/local/Cellar/libiomp/20150701/include/libiomp -L. -lc++ -lSystem
Undefined symbols for architecture x86_64:
  "__ZNSt12length_errorD1Ev", referenced from:
      __ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv in NativeOps.cpp.o
  "__ZSt9terminatev", referenced from:
      ___clang_call_terminate in NativeOps.cpp.o
  "__ZTISt12length_error", referenced from:
      __ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv in NativeOps.cpp.o
  "__ZTVSt12length_error", referenced from:
      __ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv in NativeOps.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)

```

maybe some one can see what is going wrong here? Is it trying to link with the wrong lib folders?
I hate C/C++ linking, and now here I am stuck again! :(

**Comment by Sitin** [comment]
Same issue.
After fixing paths I still have:
```sh
$ ./buildnativeoperations.sh blas cpu
LIBND4J_HOME IS /Users/sitin/Documents/Workspace/dlf4/libnd4j
eval cmake
RUNNING OSX CLANG
Running blas
RUNNING COMMAND cmake
dyld: Symbol not found: ___cxa_bad_typeid
  Referenced from: /usr/lib/libicucore.A.dylib
  Expected in: /usr/local/Cellar/clang-omp/2015-04-01/libexec/lib/libc++.1.dylib
 in /usr/lib/libicucore.A.dylib
./buildnativeoperations.sh: line 144:  7095 Trace/BPT trap: 5       cmake -DCPU_BLAS=true -DBLAS=TRUE ../..
make: *** No targets specified and no makefile found.  Stop.
FINISHING BUILD
```

**Comment by sadatanwer** [comment]
I also tried building the CUDA backend on my work windows PC just now, (I have the CPU working fine) and I get the following errors. 
https://gist.github.com/sadatanwer/773a2b39aebd19fa480c802e1ec22d5e

Its some compile errors, and I think its because of the constexpr because the compiler cant recognize it? I am not sure, but at least that is where one of the errors is (otype.h:10). I did follow the instructions maybe some how the build script is using some old cl that I have installed? can some one confirm, or tell me where (how) to look for that. 
Thanks

**Comment by saudet** [comment]
@sadatanwer Windows build is fixed: #107

**Comment by sadatanwer** [comment]
@saudet thank, Ill look at that in a few hours when I wake up and head back to work, but it looks like it should work now. 
in the mean time I am still not giving up on my trusty mac so I looked around on the internet, and based on this answer http://stackoverflow.com/questions/25020140/undefined-symbols-for-architecture-x86-64-mavericks-yosemite-el-capitan I did try changing the  `-stdlib=libstdc++` flag and that sort-of reduced the error, but did not completely fix it :( , now I am not sure if its a good change or a bad one, but for me, less error definitely looks better.. Still looking for a solution

```
clang-omp++  -Wall -fopenmp -L/usr/local/Cellar/libiomp/20150701/lib -fassociative-math -funsafe-math-optimizations -march=native   -O3 -ffast-math -ftree-vectorize -msse2 -dynamiclib -Wl,-headerpad_max_install_names  -o libnd4j.dylib -install_name @rpath/libnd4j.dylib CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o -framework Accelerate -framework Accelerate -stdlib=libstdc++ 
Undefined symbols for architecture x86_64:
  "__ZNSt11logic_errorC2EPKc", referenced from:
      __ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv in NativeOps.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by saudet** [comment]
@sadatanwer No, don't do libstdc++, it doesn't support C++11 well on OS X. Stick to libc++...

**Comment by sadatanwer** [comment]
Okay,
thanks a lot you guys! I finally got this to work, and I am now sure what was causing the problem. The new exports that I had made based on some previous exports specially the LIBRARY_PATH and all other LIB...._PATH were some how messing up the linking. clearing those exports and then re-running the compile stage made it fly like a bird!! I am now running it on Mac OSX! Today is my lucky day! 

Thanks

**Comment by AlexanderHagenhoff** [comment]
@SadatAnwar haha, the world is small
